name: Build DEB Package

on:
  push:
    tags:
      - '*' # This will trigger the workflow for tags like 1.0, 2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract tag name
        id: tag_name
        run: echo "::set-output name=TAG_NAME::$(git describe --tags --abbrev=0)"
      - name: Build package
        run: ./build.sh ${{ steps.tag_name.outputs.TAG_NAME }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
          release_name: Release ${{ steps.tag_name.outputs.TAG_NAME }}
          draft: false
          prerelease: false
      - name: Upload DEB Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./builds/dblaci-system_${{ steps.tag_name.outputs.TAG_NAME }}.deb
          asset_name: dblaci-system_${{ steps.tag_name.outputs.TAG_NAME }}.deb
          asset_content_type: application/vnd.debian.binary-package
